insert into Animal values(1, 'Rooster', 'Danish', 'kykyliky');
insert into Animal values(2, 'Rooster', 'Dutch', 'kukeleku');
insert into Animal values(3, 'Rooster','Finnish', 'kukko kiekuu');
insert into Animal values(4, 'Rooster','French', 'cocorico');
insert into Animal values(5, 'Rooster','German', 'kikeriki');
insert into Animal values(6, 'Rooster','Hebrew', 'coo-koo-ri-koo');
insert into Animal values(7, 'Rooster','Italian', 'chicchirichi');
insert into Animal values(8, 'Rooster','Japanese', 'ko-ke-kok-ko-o');
insert into Animal values(9, 'Rooster','Portuguese', 'cucurucu');
insert into Animal values(10, 'Rooster','Russian', 'kukareku');
insert into Animal values(11, 'Rooster','Swedish', 'kuckeliku');
insert into Animal values(12, 'Rooster','Turkish', 'kuk-kurri-kuuu');
insert into Animal values(13, 'Rooster','Urdu', 'kuklooku');
